#include "config_utils.h"
#include <sys/stat.h>
#include <unistd.h>
#include <pwd.h>
#include <fstream>
#include <string>

std::string get_config_path() {
    const char* home = std::getenv("HOME");
    if (!home) {
        struct passwd* pw = getpwuid(getuid());
        if (!pw) {
            return "";
        }
        home = pw->pw_dir;
    }
    return std::string(home) + "/.prompt_config";
}

bool file_exists(const std::string& path) {
    struct stat buffer;
    return stat(path.c_str(), &buffer) == 0;
}

bool create_default_config(const std::string& path) {
    std::ofstream file(path);
    if (!file.is_open()) {
        return false;
    }
    
    file << "# Prompt Configuration\n";
    file << "# Auto-generated by colorc\n\n";
    file << "default: ┌──[<user>–<computer>]──[<path>]\\n└──<$>\n";
    file << "frame: ─;┌;└;[;];–\n";
    file << "user: <user>\n";
    file << "computer: <computer>\n";
    file << "path: <path>\n";
    file << "symbol$: <$>\n";
    file.close();
    
    return true;
}

std::string read_file_content(const std::string& path) {
    std::ifstream file(path);
    if (!file.is_open()) {
        return "";
    }
    
    std::string content;
    std::string line;
    while (std::getline(file, line)) {
        content += line + "\n";
    }
    
    file.close();
    return content;
}

bool write_file_content(const std::string& path, const std::string& content) {
    std::ofstream file(path);
    if (!file.is_open()) {
        return false;
    }
    
    file << content;
    file.close();
    return true;
}

bool backup_config_file(const std::string& path) {
    if (!file_exists(path)) {
        return true;
    }
    
    std::string backup_path = path + ".backup";
    std::string content = read_file_content(path);
    
    if (content.empty()) {
        return false;
    }
    
    return write_file_content(backup_path, content);
}

std::string get_home_directory() {
    const char* home = std::getenv("HOME");
    if (!home) {
        struct passwd* pw = getpwuid(getuid());
        if (!pw) {
            return "";
        }
        home = pw->pw_dir;
    }
    return std::string(home);
}