#include "config_main.h"
#include "config_parser.h"
#include "config_validator.h"
#include "config_cache.h"
#include "config_utils.h"
#include "error.h"
#include "colors.h"
#include <algorithm>
#include <fstream>

static bool load_config_internal(const std::string& config_path) {
    if (!file_exists(config_path)) {
        if (!create_default_config(config_path)) {
            return false;
        }
    }
    
    std::map<std::string, UserConfig> all_configs = parse_config_file(config_path);
    
    clear_cache();
    for (const auto& pair : all_configs) {
        cache_user_config(pair.first, pair.second);
    }
    
    update_cache_timestamp(config_path);
    return true;
}

static std::string get_or_init_config_path() {
    static std::string config_path;
    
    if (config_path.empty()) {
        config_path = get_config_path();
    }
    
    return config_path;
}

UserConfig get_user_config(const std::string& username) {
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        UserConfig empty;
        empty.colors_user = -1;
        empty.colors_computer = -1;
        empty.colors_path = -1;
        empty.colors_symbol = -1;
        return empty;
    }
    
    if (!is_cache_valid(config_path)) {
        if (!load_config_internal(config_path)) {
            UserConfig empty;
            empty.colors_user = -1;
            empty.colors_computer = -1;
            empty.colors_path = -1;
            empty.colors_symbol = -1;
            return empty;
        }
    }
    
    UserConfig config;
    if (get_cached_config(username, config)) {
        return config;
    }
    
    UserConfig empty;
    empty.colors_user = -1;
    empty.colors_computer = -1;
    empty.colors_path = -1;
    empty.colors_symbol = -1;
    return empty;
}

bool add_new_user(const std::string& username) {
    if (username.empty()) {
        return false;
    }
    
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return false;
    }
    
    if (has_config_in_cache(username)) {
        return true;
    }
    
    if (!is_cache_valid(config_path)) {
        if (!load_config_internal(config_path)) {
            return false;
        }
    }
    
    if (has_config_in_cache(username)) {
        return true;
    }
    
    std::map<std::string, UserConfig> all_configs = parse_config_file(config_path);
    
    if (all_configs.find(username) != all_configs.end()) {
        cache_user_config(username, all_configs[username]);
        return true;
    }
    
    if (all_configs.find("default") == all_configs.end()) {
        return false;
    }
    
    UserConfig default_config = all_configs["default"];
    
    ErrorCode error;
    if (!validate_user_config(default_config, error)) {
        return false;
    }
    
    if (!save_user_config(config_path, username, default_config)) {
        return false;
    }
    
    remove_from_cache(username);
    invalidate_cache();
    
    return true;
}

bool update_user_config(const std::string& username, const UserConfig& config) {
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return false;
    }
    
    ErrorCode error;
    if (!validate_user_config(config, error)) {
        return false;
    }
    
    std::map<std::string, UserConfig> all_configs = parse_config_file(config_path);
    all_configs[username] = config;
    
    std::ofstream file(config_path);
    if (!file.is_open()) {
        return false;
    }
    
    file << "# Prompt Configuration\n";
    file << "# Auto-generated by colorc\n\n";
    
    for (const auto& pair : all_configs) {
        file << pair.first << ": " << pair.second.template_string << "\n";
        
        for (size_t i = 0; i < pair.second.frame_sections.size(); ++i) {
            const auto& section = pair.second.frame_sections[i];
            file << "frame" << (i + 1) << ": ";
            for (size_t j = 0; j < section.symbols.size(); ++j) {
                file << section.symbols[j];
                if (j < section.symbols.size() - 1) file << ";";
            }
            file << "\n";
            file << "colors_frame" << (i + 1) << ": " << section.color << "\n";
        }
        
        if (!pair.second.user_tag.empty()) {
            file << "user: " << pair.second.user_tag << "\n";
        }
        
        if (pair.second.colors_user != -1) {
            file << "colors_user: " << pair.second.colors_user << "\n";
        }
        
        if (!pair.second.computer_tag.empty()) {
            file << "computer: " << pair.second.computer_tag << "\n";
        }
        
        if (pair.second.colors_computer != -1) {
            file << "colors_computer: " << pair.second.colors_computer << "\n";
        }
        
        if (!pair.second.path_tag.empty()) {
            file << "path: " << pair.second.path_tag << "\n";
        }
        
        if (pair.second.colors_path != -1) {
            file << "colors_path: " << pair.second.colors_path << "\n";
        }
        
        if (!pair.second.symbol_tag.empty()) {
            file << "symbol$: " << pair.second.symbol_tag << "\n";
        }
        
        if (pair.second.colors_symbol != -1) {
            file << "colors_symbol$: " << pair.second.colors_symbol << "\n";
        }
        
        file << "\n";
    }
    
    file.close();
    
    remove_from_cache(username);
    invalidate_cache();
    
    return true;
}

bool delete_user_config(const std::string& username) {
    if (username == "default") {
        return false;
    }
    
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return false;
    }
    
    std::map<std::string, UserConfig> all_configs = parse_config_file(config_path);
    
    if (all_configs.find(username) == all_configs.end()) {
        return true;
    }
    
    all_configs.erase(username);
    
    std::ofstream file(config_path);
    if (!file.is_open()) {
        return false;
    }
    
    file << "# Prompt Configuration\n";
    file << "# Auto-generated by colorc\n\n";
    
    for (const auto& pair : all_configs) {
        file << pair.first << ": " << pair.second.template_string << "\n";
        
        for (size_t i = 0; i < pair.second.frame_sections.size(); ++i) {
            const auto& section = pair.second.frame_sections[i];
            file << "frame" << (i + 1) << ": ";
            for (size_t j = 0; j < section.symbols.size(); ++j) {
                file << section.symbols[j];
                if (j < section.symbols.size() - 1) file << ";";
            }
            file << "\n";
            file << "colors_frame" << (i + 1) << ": " << section.color << "\n";
        }
        
        if (!pair.second.user_tag.empty()) {
            file << "user: " << pair.second.user_tag << "\n";
        }
        
        if (pair.second.colors_user != -1) {
            file << "colors_user: " << pair.second.colors_user << "\n";
        }
        
        if (!pair.second.computer_tag.empty()) {
            file << "computer: " << pair.second.computer_tag << "\n";
        }
        
        if (pair.second.colors_computer != -1) {
            file << "colors_computer: " << pair.second.colors_computer << "\n";
        }
        
        if (!pair.second.path_tag.empty()) {
            file << "path: " << pair.second.path_tag << "\n";
        }
        
        if (pair.second.colors_path != -1) {
            file << "colors_path: " << pair.second.colors_path << "\n";
        }
        
        if (!pair.second.symbol_tag.empty()) {
            file << "symbol$: " << pair.second.symbol_tag << "\n";
        }
        
        if (pair.second.colors_symbol != -1) {
            file << "colors_symbol$: " << pair.second.colors_symbol << "\n";
        }
        
        file << "\n";
    }
    
    file.close();
    
    remove_from_cache(username);
    invalidate_cache();
    
    return true;
}

void reload_config() {
    std::string config_path = get_or_init_config_path();
    
    if (!config_path.empty()) {
        load_config_internal(config_path);
    }
}

std::vector<std::string> get_all_users() {
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return {};
    }
    
    if (!is_cache_valid(config_path)) {
        if (!load_config_internal(config_path)) {
            return {};
        }
    }
    
    return get_cached_users();
}

bool has_user_config(const std::string& username) {
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return false;
    }
    
    if (!is_cache_valid(config_path)) {
        if (!load_config_internal(config_path)) {
            return false;
        }
    }
    
    return has_config_in_cache(username);
}