#include "config_main.h"
#include "config_parser.h"
#include "config_validator.h"
#include "config_cache.h"
#include "config_utils.h"
#include "error.h"
#include <algorithm>
#include <fstream>

static bool load_config_internal(const std::string& config_path) {
    if (!file_exists(config_path)) {
        if (!create_default_config(config_path)) {
            return false;
        }
    }
    
    std::map<std::string, UserConfig> all_configs = parse_config_file(config_path);
    
    clear_cache();
    for (const auto& pair : all_configs) {
        cache_user_config(pair.first, pair.second);
    }
    
    update_cache_timestamp(config_path);
    return true;
}

static std::string get_or_init_config_path() {
    static std::string config_path;
    
    if (config_path.empty()) {
        config_path = get_config_path();
    }
    
    return config_path;
}

UserConfig get_user_config(const std::string& username) {
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return UserConfig();
    }
    
    if (!is_cache_valid(config_path)) {
        if (!load_config_internal(config_path)) {
            return UserConfig();
        }
    }
    
    UserConfig config;
    if (get_cached_config(username, config)) {
        return config;
    }
    
    return UserConfig();
}

bool add_new_user(const std::string& username) {
    if (username.empty()) {
        return false;
    }
    
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return false;
    }
    
    if (has_config_in_cache(username)) {
        return true;
    }
    
    if (!is_cache_valid(config_path)) {
        if (!load_config_internal(config_path)) {
            return false;
        }
    }
    
    if (has_config_in_cache(username)) {
        return true;
    }
    
    std::map<std::string, UserConfig> all_configs = parse_config_file(config_path);
    
    if (all_configs.find(username) != all_configs.end()) {
        cache_user_config(username, all_configs[username]);
        return true;
    }
    
    if (all_configs.find("default") == all_configs.end()) {
        return false;
    }
    
    UserConfig default_config = all_configs["default"];
    
    ErrorCode error;
    if (!validate_user_config(default_config, error)) {
        return false;
    }
    
    if (!save_user_config(config_path, username, default_config)) {
        return false;
    }
    
    remove_from_cache(username);
    invalidate_cache();
    
    return true;
}

bool update_user_config(const std::string& username, const UserConfig& config) {
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return false;
    }
    
    ErrorCode error;
    if (!validate_user_config(config, error)) {
        return false;
    }
    
    std::map<std::string, UserConfig> all_configs = parse_config_file(config_path);
    all_configs[username] = config;
    
    std::ofstream file(config_path);
    if (!file.is_open()) {
        return false;
    }
    
    file << "# Prompt Configuration\n";
    file << "# Auto-generated by colorc\n\n";
    
    for (const auto& pair : all_configs) {
        file << pair.first << ": " << pair.second.template_string << "\n";
        file << "frame: ";
        for (size_t i = 0; i < pair.second.frame_symbols.size(); ++i) {
            file << pair.second.frame_symbols[i];
            if (i < pair.second.frame_symbols.size() - 1) file << ";";
        }
        file << "\n";
        file << "user: " << pair.second.user_tag << "\n";
        file << "computer: " << pair.second.computer_tag << "\n";  
        file << "path: " << pair.second.path_tag << "\n";
        file << "symbol$: " << pair.second.symbol_tag << "\n\n";
    }
    
    file.close();
    
    remove_from_cache(username);
    invalidate_cache();
    
    return true;
}

bool delete_user_config(const std::string& username) {
    if (username == "default") {
        return false;
    }
    
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return false;
    }
    
    std::map<std::string, UserConfig> all_configs = parse_config_file(config_path);
    
    if (all_configs.find(username) == all_configs.end()) {
        return true;
    }
    
    all_configs.erase(username);
    
    std::ofstream file(config_path);
    if (!file.is_open()) {
        return false;
    }
    
    file << "# Prompt Configuration\n";
    file << "# Auto-generated by colorc\n\n";
    
    for (const auto& pair : all_configs) {
        file << pair.first << ": " << pair.second.template_string << "\n";
        file << "frame: ";
        for (size_t i = 0; i < pair.second.frame_symbols.size(); ++i) {
            file << pair.second.frame_symbols[i];
            if (i < pair.second.frame_symbols.size() - 1) file << ";";
        }
        file << "\n";
        file << "user: " << pair.second.user_tag << "\n";
        file << "computer: " << pair.second.computer_tag << "\n";  
        file << "path: " << pair.second.path_tag << "\n";
        file << "symbol$: " << pair.second.symbol_tag << "\n\n";
    }
    
    file.close();
    
    remove_from_cache(username);
    invalidate_cache();
    
    return true;
}

void reload_config() {
    std::string config_path = get_or_init_config_path();
    
    if (!config_path.empty()) {
        load_config_internal(config_path);
    }
}

std::vector<std::string> get_all_users() {
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return {};
    }
    
    if (!is_cache_valid(config_path)) {
        if (!load_config_internal(config_path)) {
            return {};
        }
    }
    
    return get_cached_users();
}

bool has_user_config(const std::string& username) {
    std::string config_path = get_or_init_config_path();
    
    if (config_path.empty()) {
        return false;
    }
    
    if (!is_cache_valid(config_path)) {
        if (!load_config_internal(config_path)) {
            return false;
        }
    }
    
    return has_config_in_cache(username);
}