#include <iostream>
#include <fstream>
#include <string>
#include <map>
#include <vector>
#include <sstream>
#include <algorithm>
#include <sys/stat.h>
#include <unistd.h>
#include <pwd.h>
#include "config.h"

std::string config_path;
std::map<std::string, UserConfig> config_cache;

std::string get_config_path() {
    const char* home = std::getenv("HOME");
    if (!home) {
        struct passwd* pw = getpwuid(getuid());
        home = pw->pw_dir;
    }
    return std::string(home) + "/.prompt_config";
}

bool file_exists(const std::string& path) {
    struct stat buffer;
    return stat(path.c_str(), &buffer) == 0;
}

void create_default_config() {
    std::ofstream file(config_path);
    if (!file.is_open()) {
        return;
    }
    
    file << "# Prompt Configuration\n";
    file << "# Auto-generated by colorc\n\n";
    file << "default: ┌──[<user>]──[<path>]\\n└──<$>\n";
    file << "frame: ─;┌;└;[;];\n";
    file << "user: <user>\n";
    file << "path: <path>\n";
    file << "symbol$: $\n";
    file.close();
}

std::vector<std::string> split(const std::string& str, char delimiter) {
    std::vector<std::string> tokens;
    std::stringstream ss(str);
    std::string token;
    while (std::getline(ss, token, delimiter)) {
        if (!token.empty()) tokens.push_back(token);
    }
    return tokens;
}

UserConfig parse_user_config(const std::vector<std::string>& lines) {
    UserConfig config;
    
    for (const auto& line : lines) {
        if (line.find(": ") == std::string::npos) continue;
        
        size_t pos = line.find(": ");
        std::string key = line.substr(0, pos);
        std::string value = line.substr(pos + 2);
        
        if (key == "frame") {
            config.frame_symbols = split(value, ';');
        } else if (key == "user") {
            config.user_tag = value;
        } else if (key == "path") {
            config.path_tag = value;
        } else if (key == "symbol$") {
            config.symbol_tag = value;
        } else {
            if (value.front() == '"' && value.back() == '"') {
                value = value.substr(1, value.length() - 2);
            }
            config.template_string = value;
        }
    }
    
    return config;
}

void load_config() {
    if (!file_exists(config_path)) {
        create_default_config();
    }
    
    std::ifstream file(config_path);
    if (!file.is_open()) {
        return;
    }
    
    std::string line;
    std::string current_user;
    std::vector<std::string> current_lines;
    
    while (std::getline(file, line)) {
        if (line.empty() || line[0] == '#') continue;
        
        if (line.find(": ") != std::string::npos) {
            size_t pos = line.find(": ");
            std::string key = line.substr(0, pos);
            
            if (key != "frame" && key != "user" && key != "path" && key != "symbol$") {
                if (!current_user.empty()) {
                    config_cache[current_user] = parse_user_config(current_lines);
                    current_lines.clear();
                }
                current_user = key;
                current_lines.push_back(line);
            } else if (!current_user.empty()) {
                current_lines.push_back(line);
            }
        } else if (!current_user.empty()) {
            current_lines.push_back(line);
        }
    }
    
    if (!current_user.empty()) {
        config_cache[current_user] = parse_user_config(current_lines);
    }
    
    file.close();
}

UserConfig get_user_config(const std::string& username) {
    if (config_cache.empty()) {
        config_path = get_config_path();
        load_config();
    }
    
    if (config_cache.find(username) != config_cache.end()) {
        return config_cache[username];
    }
    
    return UserConfig();
}

bool add_new_user(const std::string& username) {
    UserConfig default_config = get_user_config("default");
    if (default_config.template_string.empty()) {
        return false;
    }
    
    std::ofstream file(config_path, std::ios::app);
    if (!file.is_open()) {
        return false;
    }
    
    file << "\n" << username << ": " << default_config.template_string << "\n";
    file << "frame: ";
    for (size_t i = 0; i < default_config.frame_symbols.size(); ++i) {
        file << default_config.frame_symbols[i];
        if (i < default_config.frame_symbols.size() - 1) file << ";";
    }
    file << "\n";
    file << "user: " << default_config.user_tag << "\n";
    file << "path: " << default_config.path_tag << "\n";
    file << "symbol$: " << default_config.symbol_tag << "\n";
    
    file.close();
    
    config_cache.clear();
    load_config();
    
    return true;
}