#ifndef ERROR_H
#define ERROR_H

enum ErrorCode {
    SUCCESS = 0,
    ERROR_USERNAME_NOT_FOUND,
    ERROR_CONFIG_PERMISSION_DENIED,
    ERROR_CONFIG_READ_FAILED,
    ERROR_CONFIG_PARSE_FAILED,
    ERROR_FRAME_SYMBOLS_INVALID,
    ERROR_FRAME_SYMBOLS_CONTENT,
    ERROR_FRAME_TEMPLATE_MISMATCH,
    ERROR_USER_TAG_MISMATCH,
    ERROR_PATH_TAG_MISMATCH,
    ERROR_SYMBOL_TAG_MISMATCH,
    ERROR_TEMPLATE_INVALID,
    ERROR_TEMPLATE_FORMAT_INVALID,
    ERROR_TAG_EMPTY,
    ERROR_TAG_INVALID,
    ERROR_TAG_BRACKETS,
    ERROR_ESCAPE_INVALID,
    ERROR_MEMORY_ALLOCATION,
    ERROR_UNKNOWN
};

const char* get_error_message(ErrorCode code);
const char* get_error_description(ErrorCode code);
void print_error(ErrorCode code);

#endif